# Reference:
# mkdocs - https://www.mkdocs.org/user-guide/configuration/
# mkdocs material theme - https://squidfunk.github.io/mkdocs-material/getting-started/#configuration
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project Information
site_name: pyalgotrading
site_description: Official Python Package for Algorithmic Trading APIs powered by AlgoBulls
site_author: Pushpak Dagade (pushpak@algobulls.com)
site_url: https://algobulls.github.io/pyalgotrading/

# GitHub Repo information
repo_url: https://github.com/algobulls/pyalgotrading

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - tabs

  favicon: 'https://algobulls.com/img/favicon.svg'
  logo: 'algobulls_logo.svg'
  palette:
    primary: blue
    accent: blue
#    scheme: slate       # dark mode
    scheme: default     # light mode
  language: en

  collapse_navigation: False
  sticky_navigation: True

copyright: Copyright Â© 2020 | All Rights Reserved | AlgoBulls Technologies Private Limited

# Navigation
nav:
  - Home: 'index.md'
  - Pyalgotrading:
#    - Comprehensive Guide to pyalgotrading: 'pyalgotrad/python_build_comprehensive_guide.md'
    - Introduction: 'pyalgotrad/introduction.md'
    - Setup your Workspace: 'pyalgotrad/prerequisites.md'
    - Strategy Creation and Execution:
          - Code Structure of Strategy: 'pyalgotrad/strategy_guides/structure.md'
          - Create your Strategy:
            - Regular Strategy: 'pyalgotrad/strategy_guides/common_regular_strategy.md'
            - Options Strategy: 'pyalgotrad/strategy_guides/common_options_strategy.md'
          - Upload your Strategy: 'pyalgotrad/upload.md'
          - Select your Strategy: 'pyalgotrad/select.md'
          - Execute your Strategy: 'pyalgotrad/testing.md'
    - Analytics:
      - Analytics in pyalgotrading: 'pyalgotrad/pyalgotrading_analytics.md'
      - Analytics in AlgoBulls Platform: 'pyalgotrad/python-build-view-results.md'
  - Python Build Web:
      - Introduction: 'python_build/python-build-introduction.md'
#        - Introduction: 'python_build/python-build-introduction.md'
#        - Overview: 'python_build/python-build-overview.md'
      - Setup your Workspace:  'python_build/python-build-getstarted.md'
      - Strategy Creation and Execution:
          - Code Structure of Strategy: 'python_build/strategy_guides/structure.md'
          - Create your Strategy:
            - Code Using AI: 'python_build/python-build-code-gen-ai.md'
            - Code Ready Templates: 'python_build/python-build-code-ready-templates.md'
            - Code New Strategy: 'python_build/python-build-code-new.md'
            - Regular Strategy: 'python_build/strategy_guides/common_regular_strategy.md'
            - Options Strategy: 'python_build/strategy_guides/common_options_strategy.md'
          - Configure and Execute your Strategy: 'python_build/python-build-config-parameters.md'
      - Analytics:
          - Analytics in pyalgotrading: 'python_build/pyalgotrading_analytics.md'
          - Analytics in AlgoBulls Platform: 'python_build/python-build-view-results.md'
  - Strategies:
      - General Strategy Guide:
          - Code Structure of Strategy: 'strategies/strategy_guides/structure.md'
          - Regular Strategy: 'strategies/strategy_guides/common_regular_strategy.md'
          - Options Strategy: 'strategies/strategy_guides/common_options_strategy.md'
      - Regular Strategies:
          - Aroon Crossover: 'strategies/aroon_crossover.md'
          - Bollinger Bands: 'strategies/bollinger_bands.md'
          - EMA Crossover: 'strategies/ema_crossover.md'
          - Inverse EMA Scalping: 'strategies/inverse_ema_scalping.md'
          - Reverse RSI: 'strategies/reverse_rsi.md'
          - Stochastic Crossover: 'strategies/stochastic_crossover.md'
          - VWAP Crossover: 'strategies/vwap_crossover.md'
      - Options Strategies:
          - Options Bear Call Ladder: 'strategies/options_bear_call_ladder.md'
          - Options Bear Put Ladder: 'strategies/options_bear_put_ladder.md'
          - Options Bull Call Ladder: 'strategies/options_bull_call_ladder.md'
          - Options Bull Put Ladder: 'strategies/options_bull_put_ladder.md'
          - Options Long Iron Butterfly: 'strategies/options_long_iron_butterfly.md'
          - Options Straddle: 'strategies/options_straddle.md'
          - Options Strangle: 'strategies/options_strangle.md'
  - Brokers:
      - Alpaca: 'brokers/broker_alpaca_guide.md'
  - Gen AI:
      - Create your OpenAI Keys: 'gen_ai/get_open_ai_keys.md'
      - Prompt Library: 'gen_ai/gen_ai_prompt_library.md'
plugins:
  - search                                  # necessary for search to work
  - git-revision-date-localized:            # When enabled, the respective 'Last Updated' date is automatically added at the bottom of each page. Docs: https://squidfunk.github.io/mkdocs-material/plugins/revision-date/
      type: timeago
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - pyalgotrading
  - redirects:
      redirect_maps:
          'strategies/common_regular_strategy.md': 'strategies/strategy_guides/common_regular_strategy.md'
          'strategies/common_options_strategy.md': 'strategies/strategy_guides/common_options_strategy.md'

google_analytics:
  - 'UA-147658856-4'
  - 'auto'

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/algobulls
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/algobullsalgotrading
    - icon: fontawesome/brands/github-alt
      link: https://github.com/algobulls/
  disqus: algobulls

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - admonition              # Add note, tip, question, warning, error, etc. Docs: https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - attr_list
  - codehilite
  - md_in_html
  - def_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
#      anchor_linenums: true
  - toc:                    # Docs: https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      auto_title: false
      pygments_lang_class: true